export const MAP_BOUNDS_WAS_CHANGED_CONSTANT = 'MAP_BOUNDS_WAS_CHANGED'
export const ADD_MARKER_CONSTANT = 'ADD_MARKER_CONSTANT'
export const REMOVE_ALL_MARKERS_CONSTANT = 'REMOVE_ALL_MARKERS_CONSTANT'
export const CHANGE_MARKERS_VISABILITY_CONSTANT = 'CHANGE_MARKERS_VISABILITY_CONSTANT'
